### ISSUE TITLE
Список категорий

### ISSUE THREAD

**Issue by brusselboy** [atls-academy/brusselboy.github.io#10]
## Описание бага

ref на оригинал - [link](https://github.com/atls/serenity/issues/165)
---

На странице http://localhost:3000/specialists некорректно отображаются разделы

### Воспроизведение

Шаги для воспроизведения бага:

1. `docker-compose up site-local`
2. `docker-compose up private-gateway`
3. Идем на http://localhost:4001/ - там создаем группы категорий и сами категории:

**Создание группы:**

```gql
mutation CreateCategoryGroup {
  createCategoryGroup(input: { name: "group" }) {
    result {
      id
    }
  }
}
```

**Создание категории:**

```gql
mutation CreateCategory {
  createCategory(
    input: {
      name: "category"
      groupId: "f31e7945-dbd3-48cd-bc47-d1bfed2838fc"
    }
  ) {
    result {
      id
    }
  }
}
```

4. После создание тестовых данных идем на http://localhost:3000/specialists
5. Ждем пока обработается запрос и справа отрисуются разделы
6. Видим, что они не соответствуют дизайну

### Ожидаемое поведение

[Дизайн](https://www.figma.com/file/4IJW62UuHqHqpSuCPPj55L/Topmasters?node-id=0%3A2629)

### Материалы

![Screenshot from 2022-05-25 16-10-08](https://user-images.githubusercontent.com/62806448/170249053-c95496c9-deb0-4c8f-8d0f-7bbed32745ad.png)

### Данные окружения

- Ubuntu@20.04
- Chrome@latest

**Comment by brusselboy** [comment]
## Не поднимается фронт и gateway
@TFK70

### Шаги

1. Сделал yarn
2. Сделал docker-compose up site-local
3. Сделал docker-compose up private-gateway

### Логи docker-compose up site-local
```
WARNING: The PUBLIC_GATEWAY_URL variable is not set. Defaulting to a blank string.
WARNING: The DEV_AUTH_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The DEV_AUTH_USER variable is not set. Defaulting to a blank string.
WARNING: The GCS_BUCKET variable is not set. Defaulting to a blank string.
serenity_redis_1 is up-to-date
serenity_traefik_1 is up-to-date
Starting serenity_site-local_1 ... done
Attaching to serenity_site-local_1
site-local_1 | Browserslist: caniuse-lite is outdated. Please run:
site-local_1 | npx browserslist@latest --update-db
site-local_1 | warn - You have enabled experimental feature(s).
site-local_1 | warn - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
site-local_1 |
site-local_1 | ready - started server on http://localhost:3000
site-local_1 | event - compiled successfully
site-local_1 | (node:45) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
site-local_1 | (Use `node --trace-warnings ...` to show where the warning was created)

```

### Логи docker-compose up private-gateway
```
WARNING: The PUBLIC_GATEWAY_URL variable is not set. Defaulting to a blank string.
WARNING: The DEV_AUTH_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The DEV_AUTH_USER variable is not set. Defaulting to a blank string.
WARNING: The GCS_BUCKET variable is not set. Defaulting to a blank string.
Starting serenity_private-gateway_1 ... done
Attaching to serenity_private-gateway_1
private-gateway_1 | Failed to compile.
private-gateway_1 |
private-gateway_1 | /workspace/.yarn/__virtual__/@graphql-tools-utils-virtual-31d520ef45/0/cache/@graphql-tools-utils-npm-8.6.1-012acc0b32-1286a2a616.zip/node_modules/@graphql-tools/utils/index.mjs
private-gateway_1 | Can't import the named export 'GraphQLBoolean' from non EcmaScript module (only default export is available)
private-gateway_1 | Starting the development server...
private-gateway_1 |
private-gateway_1 | /workspace/.pnp.cjs:54150
private-gateway_1 | throw firstError;
private-gateway_1 | ^
private-gateway_1 |
private-gateway_1 | Error: Your application tried to access ts-node, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
private-gateway_1 |
private-gateway_1 | Required package: ts-node (via "ts-node/register")
private-gateway_1 | Required by: /workspace/backend/private-gateway/app/
private-gateway_1 |
private-gateway_1 | Require stack:
private-gateway_1 | - internal/preload
private-gateway_1 | at Function.require$$0.Module._resolveFilename (/workspace/.pnp.cjs:54149:13)
private-gateway_1 | at Function.require$$0.Module._load (/workspace/.pnp.cjs:54003:42)
private-gateway_1 | at Module.require (node:internal/modules/cjs/loader:1005:19)
private-gateway_1 | at Module._preloadModules (node:internal/modules/cjs/loader:1282:12)
private-gateway_1 | at loadPreloadModules (node:internal/bootstrap/pre_execution:539:5)
private-gateway_1 | at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:85:3)
private-gateway_1 | at node:internal/main/run_main_module:7:1

```

**Comment by TFK70** [comment]
@brusselboy нужно запускаться в [этой](https://github.com/atls/serenity/pull/164) ветке

**Comment by brusselboy** [comment]
## Крашится браузер с IDE
@TFK70 

### Описание
Когда поднимаешь докер `docker-compose up site-local` и `docker-compose up private-gateway` крашится браузер и ide

### Материалы

https://user-images.githubusercontent.com/35490768/171154949-1020e484-730b-4f00-a826-df1709abcff8.mp4

**Comment by TorinAsakura** [comment]
@TFK70 Повысь размер памяти для IDE
